from typing import Final

from src.helper_config import ConfigGetJson, get_parser


class Config:
    TCP_LIMIT: int = ConfigGetJson.Get.tcp_limit()
    LIMIT_PER: int = ConfigGetJson.Get.limit_per()
    RESPONSE_TIME: float = ConfigGetJson.Get.response_time()
    PARSER: str = get_parser()
    TIMEOUT: int = ConfigGetJson.Get.timeout()
    URL_BASE: Final[str] = "https://fragment.com/"
    DEFAULT_STATUS: str = ConfigGetJson.Get.default_status()
    en_list: Final = [
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p",
        "a",
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l",
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
    ]  # список англиских букв
    special_chars: Final = [
        "!",
        '"',
        "№",
        ";",
        "%",
        ":",
        "?",
        "*",
        "(",
        ")",
        "+",
        "{",
        "}",
        "[",
        "]",
        "#",
        "$",
        "^",
        "&",
        "-",
        "<",
        ">",
        ",",
        "/",
        "|",
        "\\",
        "`",
        "~",
        ".",
    ]  # спец симвулы и прочие знаки которые запрещены в юзах
    ru_chars: Final = [
        "й",
        "ц",
        "у",
        "к",
        "е",
        "н",
        "г",
        "ш",
        "щ",
        "з",
        "х",
        "ф",
        "ы",
        "в",
        "а",
        "п",
        "р",
        "о",
        "л",
        "д",
        "я",
        "ж",
        "ч",
        "с",
        "м",
        "и",
        "т",
        "ь",
        "б",
        "ю",
        "ё",
        "Ъ",
    ]
